### ISSUE TITLE
Improve the UI 

### ISSUE THREAD

**Issue by jaibhedia** [jaibhedia/NBP_NFT#1]
Make the UI more beautiful and functional.

**Comment by NandishM0618** [comment]
@jaibhedia please assign this issue to me I would like to work on it.

**Comment by NandishM0618** [comment]
@jaibhedia I have made pull request please review it #2 if any changes required please update me.

**Comment by jaibhedia** [comment]
@NandishM0618 Sure, will review the PR and let you know if any changes are required.

**Comment by NandishM0618** [comment]
@jaibhedia I have made a pull request please review it #3 if any changes required please update me.

**Comment by NandishM0618** [comment]
@jaibhedia I have resolved the loading issue please review it #5
